# Generated by Django 4.2.6 on 2023-10-23 03:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('birth_at', models.DateField()),
                ('login', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must be at least 8 characters long and contain at least one letter and one number', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
    ]
